window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isiOS=!1;if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){window.isiOS=!0}
window.isiOSVersion='';if(window.isiOS){var version=(navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);if(version!==null){window.isiOSVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t602_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var indicator=rec.querySelector('.t602__indicator');if(!indicator)return;window.addEventListener('scroll',t_throttle(function(){var documentHeight=document.body.clientHeight;var windowScrollTop=document.documentElement.scrollTop;var windowHeight=window.innerHeight;var scrollPercent=(windowScrollTop/(documentHeight-windowHeight))*100;indicator.style.width=scrollPercent+'%'},100))}
function t983_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t983');if(!container)return;window.addEventListener('resize',t_throttle(function(){if(window.noAdaptive&&window.noAdaptive===!0&&window.isMobile)return;t983_unifyHeights(recId);t983_translateBlock(recId)}));window.addEventListener('load',function(){t983_unifyHeights(recId);t983_translateBlock(recId)});container.addEventListener('displayChanged',t_throttle(function(){t983_unifyHeights(recId);t983_translateBlock(recId)}));t983_unifyHeights(recId);t983_translateBlock(recId);t983__updateLazyLoad(recId)}
function t983_translateBlock(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t983');if(!container)return;var hoverBlocks=rec.querySelectorAll('.t983__card-block_hover');var wrapMarginBottom=35;var isMobile=window.isMobile||window.innerWidth<960;for(var i=0;i<hoverBlocks.length;i++){var hoverBlock=hoverBlocks[i];var blockWrapper=t983_getParent(hoverBlock,'t983__card-block-wrapper');var card=t983_getParent(hoverBlock,'t983__card');var cardHeight=card.clientHeight;var diff=cardHeight-hoverBlock.offsetHeight-wrapMarginBottom*2;var cardHideDiff=hoverBlock.querySelector('.t983__card-hide').offsetHeight;blockWrapper.style.transform='translateY('+diff+'px)';if(!isMobile){hoverBlock.style.transform='translateY('+cardHideDiff+'px)'}else{hoverBlock.style.transform=null}}
if(hoverBlocks.length===0){var rows=(isMobile?rec.querySelectorAll('.t983__container'):rec.querySelectorAll('.t983__row'));for(var i=0;i<rows.length;i++){var row=rows[i];var cardBlocks=row.querySelectorAll('.t983__card-block');var maxHeightRow=0;var card=t983_getParent(cardBlocks[0],'t983__card');if(card){var cardStyle=getComputedStyle(card,null);var cardPaddingTop=parseInt(cardStyle.paddingTop)||0;var cardPaddingBottom=parseInt(cardStyle.paddingBottom)||0;var cardHeight=card.clientHeight-(cardPaddingTop+cardPaddingBottom);for(var j=0;j<cardBlocks.length;j++){var cardHide=cardBlocks[j].querySelector('.t983__card-hide');var cardHideHeight=cardHide?cardHide.offsetHeight:0;if(cardHideHeight>maxHeightRow)maxHeightRow=cardHideHeight}
for(var j=0;j<cardBlocks.length;j++){var cardBlock=cardBlocks[j];var cardShow=cardBlock.querySelector('.t983__card-show');var cardShowHeight=cardShow?cardShow.offsetHeight:0;var diff=cardHeight-cardShowHeight-maxHeightRow-wrapMarginBottom*2;cardBlock.style.transform='translateY('+diff+'px)'}}}}}
function t983_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var main=rec.querySelector('.t983');if(!main)return;var container=rec.querySelector('.t983__container');var rows=main.querySelectorAll('.t983__row');for(var i=0;i<rows.length;i++){var row=rows[i];var cardsContent=row.querySelectorAll('.t983__card-content');var cardsWrapper=row.querySelectorAll('.t983__card-wrapper');var card=row.querySelector('.t983__card');var cardStyle=getComputedStyle(card,null);var cardPaddingLeft=parseInt(cardStyle.paddingLeft)||0;var cardPaddingRight=parseInt(cardStyle.paddingRight)||0;var cardWidth=card.clientWidth-(cardPaddingLeft+cardPaddingRight);var maxHeight=0;var ratio=container.getAttribute('data-ratio');var minHeightFromRatio=0;switch(ratio){case '16_9':minHeightFromRatio=cardWidth*0.5625;break;case '4_3':minHeightFromRatio=cardWidth*0.75;break;case '3_2':minHeightFromRatio=cardWidth*0.6666;break;case '1_1':minHeightFromRatio=cardWidth;break;case '2_3':minHeightFromRatio=cardWidth*1.5;break;case '3_4':minHeightFromRatio=cardWidth*1.3333;break;case '9_16':minHeightFromRatio=cardWidth*1.7777;break}
for(var j=0;j<cardsContent.length;j++){var cardContentHeight=cardsContent[j].offsetHeight;if(cardContentHeight>maxHeight)maxHeight=cardContentHeight}
if(maxHeight>minHeightFromRatio){for(var j=0;j<cardsWrapper.length;j++){cardsWrapper[j].style.paddingBottom=maxHeight+'px'}}else{for(var j=0;j<cardsWrapper.length;j++){cardsWrapper[j].style.paddingBottom=null}}}}
function t983__updateLazyLoad(recId){var allRecords=document.getElementById('allrecords');if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){var scrollContainer=document.querySelector('#rec'+recId+' .t983__container_mobile-flex');var curMode=allRecords.getAttribute('data-tilda-mode');if(scrollContainer&&curMode!='edit'&&curMode!='preview'&&window.isMobile){scrollContainer.addEventListener('touchmove',t_throttle(function(){t_lazyload_update()}))}})}}
function t983_getParent(element,className){for(var p=element&&element.parentElement;p;p=p.parentElement){if(p.classList.contains(className)){return p}}}
function t635_init(recid,textColor,cursorColor){var rec=document.querySelector('#rec'+recid);if(!rec)return;var typingData=rec.querySelector('.t635__textholder');if(!typingData)return;var typingRecIdList=typingData.getAttribute('data-recid').split(',');if(typingRecIdList.length===0)return;typingRecIdList.forEach(function(animRecId){var currentRecID=document.querySelector('#rec'+animRecId);if(!currentRecID)return;var screenMin=parseInt(currentRecID.getAttribute('data-screen-min'),10);var screenMax=parseInt(currentRecID.getAttribute('data-screen-max'),10);if(isNaN(screenMax)&&isNaN(screenMin)){t635_startType(recid,animRecId,textColor,cursorColor)}else if(!isNaN(screenMax)&&!isNaN(screenMin)){if(window.innerWidth>=screenMin&&window.innerWidth<=screenMax){t635_startType(recid,animRecId,textColor,cursorColor)}}else if(!isNaN(screenMax)){if(window.innerWidth<=screenMax){t635_startType(recid,animRecId,textColor,cursorColor)}}else if(!isNaN(screenMin)){if(window.innerWidth>=screenMin){t635_startType(recid,animRecId,textColor,cursorColor)}}})}
function t635_startType(recid,animRecId,textColor,cursorColor){var rec=document.querySelector('#rec'+recid);if(!rec)return;var animData=rec.querySelector('.t635__textholder');if(!animData)return;var animText=t635_findAnimElem(animRecId);var phrasesList=[];var phrase1=animData.getAttribute('data-text1');var phrase2=animData.getAttribute('data-text2');var phrase3=animData.getAttribute('data-text3');var phrase4=animData.getAttribute('data-text4');var phrase5=animData.getAttribute('data-text5');var animSpeed=animData.getAttribute('data-speed');var animLoop=animData.getAttribute('data-loop');var backspaceDelay=animData.getAttribute('data-backspacing-delay');if(!animText)return;if(typeof phrase1==='string'){phrasesList.push(phrase1.slice(0,80))}
if(typeof phrase2==='string'){phrasesList.push(phrase2.slice(0,80))}
if(typeof phrase3==='string'){phrasesList.push(phrase3.slice(0,80))}
if(typeof phrase4==='string'){phrasesList.push(phrase4.slice(0,80))}
if(typeof phrase5==='string'){phrasesList.push(phrase5.slice(0,80))}
if(animText&&phrasesList.length){var animTextHtml=animText.innerHTML;var animTextSplitted=animTextHtml.split('|');animText.innerHTML=animTextSplitted[0]+'<span class="t635__typing-text"></span>'+animTextSplitted[1];t635_updateAnimTextLimits(animRecId);t_onFuncLoad('t_throttle',function(){window.addEventListener('resize',t_throttle(function(){t635_updateAnimTextLimits(animRecId)}))});setInterval(function(){t635_updateAnimTextLimits(animRecId)},5000);var animatedText=document.querySelector('#rec'+animRecId+' .t635__typing-text');if(!animatedText)return;var animTextTop=animatedText.getAttribute('data-top-limit');var animTextBottom=animatedText.getAttribute('data-bottom-limit');var windowTop=document.querySelector('html').scrollTop;var windowBottom=windowTop+window.innerHeight;t_onFuncLoad('Typed',function(){var typedInstance=t635_animateText(animRecId,phrasesList,animSpeed,animLoop,backspaceDelay);var animatedCursor=document.querySelector('#rec'+animRecId+' .typed-cursor');if(textColor&&animatedText)animatedText.style.color=textColor;if(cursorColor&&animatedCursor)animatedCursor.style.color=cursorColor;if(animTextBottom<windowTop||animTextTop>windowBottom){typedInstance.reset();typedInstance.stop()}
var ZeroBlock=animatedText.closest('.t396');var isSBSAnimation=!1;if(ZeroBlock){var elem=animatedText.closest('.t396__elem');isSBSAnimation=elem?!!elem.getAttribute('data-animate-sbs-event'):!1}
if('IntersectionObserver' in window&&!isSBSAnimation){var observer=new IntersectionObserver(function(entries,observer){Array.prototype.forEach.call(entries,function(entry){if(entry.isIntersecting){typedInstance.start()}else{typedInstance.reset();typedInstance.stop()}})});var recT809=document.querySelector('[data-record-type="809"]');if(recT809){document.addEventListener('replacingCompletedT809',function(){observer.observe(animatedText)})}else{observer.observe(animatedText)}}else{t_onFuncLoad('t_throttle',function(){window.addEventListener('scroll',t_throttle(function(){animTextTop=animatedText.getAttribute('data-top-limit');animTextBottom=animatedText.getAttribute('data-bottom-limit');windowTop=document.querySelector('html').scrollTop;windowBottom=windowTop+window.innerHeight;if(animTextBottom<windowTop||animTextTop>windowBottom){typedInstance.reset();typedInstance.stop()}else{typedInstance.start()}},700))})}
if(ZeroBlock){var event=document.createEvent('HTMLEvents');event.initEvent('animationInited',!0,!1);window.dispatchEvent(event)}})}}
function t635_findAnimElem(animRecId){var animRec=document.querySelector('#rec'+animRecId);if(!animRec)return;var currentH1=t635_findAnimTag(animRec,'h1');var currentH2=t635_findAnimTag(animRec,'h2');var currentH3=t635_findAnimTag(animRec,'h3');var currentDiv=t635_findAnimTag(animRec,'div');if(currentH1)return currentH1;if(currentH2)return currentH2;if(currentH3)return currentH3;if(currentDiv)return currentDiv}
function t635_findAnimTag(parent,element){var allElements=parent.querySelectorAll(element);for(var i=0;i<allElements.length;i++){if(allElements[i].innerHTML.indexOf('|')!==-1&&allElements[i].innerHTML.indexOf('t-map')===-1){var lastElement=allElements[i]}}
return lastElement}
function t635_updateAnimTextLimits(animRecId){var animatedBlock=document.querySelector('#rec'+animRecId);if(!animatedBlock)return;var animatedText=animatedBlock.querySelector('.t635__typing-text');if(animatedText){animatedText.setAttribute('data-top-limit',animatedText.getBoundingClientRect().top+window.pageYOffset);animatedText.setAttribute('data-bottom-limit',animatedBlock.getBoundingClientRect().top+window.pageYOffset+animatedBlock.clientHeight)}}
function t635_animateText(animRecId,phrasesList,animSpeed,animLoop,backspaceDelay){if(!animSpeed)animSpeed=40;if(!backspaceDelay)backspaceDelay=800;if(animLoop===null)animLoop=!0;if(animLoop==='false')animLoop=!1;var animRec='#rec'+animRecId+' .t635__typing-text';return new Typed(animRec,{strings:phrasesList,typeSpeed:animSpeed*1,startDelay:600,backDelay:backspaceDelay,loop:animLoop,})}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}
function t738_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t738');if(!container)return;var items=rec.querySelectorAll('.t738__item');var maxHeight=0;for(var i=0;i<items.length;i++){items[i].style.height=''}
for(var i=0;i<items.length;i++){var itemPaddingTop=parseInt(getComputedStyle(items[i]).paddingTop)||0;var itemPaddingBottom=parseInt(getComputedStyle(items[i]).paddingBottom)||0;var imgHeight=items[i].querySelector('img').offsetHeight+itemPaddingTop+itemPaddingBottom;if(imgHeight>maxHeight){maxHeight=imgHeight}}
for(var i=0;i<items.length;i++){var itemPaddingTop=parseInt(getComputedStyle(items[i]).paddingTop)||0;var itemPaddingBottom=parseInt(getComputedStyle(items[i]).paddingBottom)||0;items[i].style.height=maxHeight+itemPaddingTop+itemPaddingBottom+'px'}
t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recId)})}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){var recBlocks=document.querySelectorAll('.r');t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});for(var i=0;i<recBlocks.length;i++){recBlocks[i].addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href$="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t702__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(recBlocks[i],popupTooltipHook)})}}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup(recId)});popupCloseBtn.addEventListener('click',function(){t702_closePopup(recId)});if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recId);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup(recId)}
popup.addEventListener('tildamodal:show'+popupTooltipHook,function(){document.addEventListener('keydown',t702_escClosePopup)});popup.addEventListener('tildamodal:close'+popupTooltipHook,function(){document.removeEventListener('keydown',t702_escClosePopup)})}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return;if(screenMax&&windowWidth>parseInt(screenMax,10))return;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var range=rec.querySelector('.t-range');var documentBody=document.body;if(range)t702__triggerEvent(range,'popupOpened');t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
t702__lazyLoad();t702__triggerEvent(popup,'tildamodal:show'+popupTooltipHook)}
function t702_closePopup(recId){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var popupAll=document.querySelectorAll('.t-popup_show:not(.t-feed__post-popup):not(.t945__popup)');if(popupAll.length==1){document.body.classList.remove('t-body_popupshowed')}else{var newPopup=[];for(var i=0;i<popupAll.length;i++){if(popupAll[i].getAttribute('data-tooltip-hook')===popupTooltipHook){popupAll[i].classList.remove('t-popup_show');newPopup.push(popupAll[i])}}
if(newPopup.length===popupAll.length){document.body.classList.remove('t-body_popupshowed')}}
popup.classList.remove('t-popup_show');document.body.classList.remove('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);t702__triggerEvent(popup,'tildamodal:close'+popupTooltipHook)}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t228__init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuBlock=rec.querySelector('.t228');var mobileMenu=rec.querySelector('.t228__mobile');var menuSubLinkItems=rec.querySelectorAll('.t-menusub__link-item');var rightBtn=rec.querySelector('.t228__right_buttons_but .t-btn');var mobileMenuPosition=mobileMenu?mobileMenu.style.position||window.getComputedStyle(mobileMenu).position:'';var mobileMenuDisplay=mobileMenu?mobileMenu.style.display||window.getComputedStyle(mobileMenu).display:'';var isFixedMobileMenu=mobileMenuPosition==='fixed'&&mobileMenuDisplay==='block';var overflowEvent=document.createEvent('Event');var noOverflowEvent=document.createEvent('Event');overflowEvent.initEvent('t228_overflow',!0,!0);noOverflowEvent.initEvent('t228_nooverflow',!0,!0);if(menuBlock){menuBlock.addEventListener('t228_overflow',function(){t228_checkOverflow(recid)});menuBlock.addEventListener('t228_nooverflow',function(){t228_checkNoOverflow(recid)})}
rec.addEventListener('click',function(e){var targetLink=e.target.closest('.t-menusub__target-link');if(targetLink&&window.isMobile){if(targetLink.classList.contains('t-menusub__target-link_active')){if(menuBlock)menuBlock.dispatchEvent(overflowEvent)}else{if(menuBlock)menuBlock.dispatchEvent(noOverflowEvent)}}
var currentLink=e.target.closest('.t-menu__link-item:not(.tooltipstered):not(.t-menusub__target-link):not(.t794__tm-link):not(.t966__tm-link):not(.t978__tm-link):not(.t978__menu-link)');if(currentLink&&mobileMenu&&isFixedMobileMenu)mobileMenu.click()});Array.prototype.forEach.call(menuSubLinkItems,function(linkItem){linkItem.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})});if(rightBtn){rightBtn.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})}
if(menuBlock){menuBlock.addEventListener('showME601a',function(){var menuLinks=rec.querySelectorAll('.t966__menu-link');Array.prototype.forEach.call(menuLinks,function(menuLink){menuLink.addEventListener('click',function(){if(mobileMenu&&isFixedMobileMenu)mobileMenu.click()})})})}}
function t228_checkOverflow(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t228'):null;if(!menu)return;var mobileContainer=document.querySelector('.t228__mobile_container');var mobileContainerHeight=t228_getFullHeight(mobileContainer);var windowHeight=document.documentElement.clientHeight;var menuPosition=menu.style.position||window.getComputedStyle(menu).position;if(menuPosition==='fixed'){menu.classList.add('t228__overflow');menu.style.setProperty('height',(windowHeight-mobileContainerHeight)+'px','important')}}
function t228_checkNoOverflow(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var menu=rec.querySelector('.t228');var menuPosition=menu?menu.style.position||window.getComputedStyle(menu).position:'';if(menuPosition==='fixed'){if(menu)menu.classList.remove('t228__overflow');if(menu)menu.style.height='auto'}}
function t228_setWidth(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menuCenterSideList=rec.querySelectorAll('.t228__centerside');Array.prototype.forEach.call(menuCenterSideList,function(menuCenterSide){menuCenterSide.classList.remove('t228__centerside_hidden')});if(window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t228');Array.prototype.forEach.call(menuBlocks,function(menu){var maxWidth;var centerWidth=0;var paddingWidth=40;var leftSide=menu.querySelector('.t228__leftside');var rightSide=menu.querySelector('.t228__rightside');var menuList=menu.querySelector('.t228__list');var mainContainer=menu.querySelector('.t228__maincontainer');var leftContainer=menu.querySelector('.t228__leftcontainer');var rightContainer=menu.querySelector('.t228__rightcontainer');var centerContainer=menu.querySelector('.t228__centercontainer');var centerContainerLi=centerContainer?centerContainer.querySelectorAll('li'):[];var leftContainerWidth=t228_getFullWidth(leftContainer);var rightContainerWidth=t228_getFullWidth(rightContainer);var mainContainerWidth=mainContainer?mainContainer.offsetWidth:0;var dataAlign=menu.getAttribute('data-menu-items-align');var isDataAlignCenter=dataAlign==='center'||dataAlign===null;maxWidth=leftContainerWidth>=rightContainerWidth?leftContainerWidth:rightContainerWidth;maxWidth=Math.ceil(maxWidth);Array.prototype.forEach.call(centerContainerLi,function(li){centerWidth+=t228_getFullWidth(li)});if(mainContainerWidth-(maxWidth*2+paddingWidth*2)>centerWidth+20){if(isDataAlignCenter){if(leftSide)leftSide.style.minWidth=maxWidth+'px';if(rightSide)rightSide.style.minWidth=maxWidth+'px'}}else{if(leftSide)leftSide.style.minWidth=maxWidth+'';if(rightSide)rightSide.style.minWidth=maxWidth+''}
if(menuList&&menuList.classList.contains('t228__list_hidden'))menuList.classList.remove('t228__list_hidden')})}
function t228_getFullWidth(el){if(!el)return 0;var marginLeft=el.style.marginLeft||window.getComputedStyle(el).marginLeft;var marginRight=el.style.marginRight||window.getComputedStyle(el).marginRight;marginLeft=parseInt(marginLeft,10)||0;marginRight=parseInt(marginRight,10)||0;return el.offsetWidth+marginLeft+marginRight}
function t228_getFullHeight(el){if(!el)return 0;var marginTop=el.style.marginTop||window.getComputedStyle(el).marginTop;var marginBottom=el.style.marginBottom||window.getComputedStyle(el).marginBottom;marginTop=parseInt(marginTop,10)||0;marginBottom=parseInt(marginBottom,10)||0;return el.offsetHeight+marginTop+marginBottom}
function t898_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t898');if(!container)return;rec.setAttribute('data-animationappear','off');rec.style.opacity=1;var whatsApp=rec.querySelector('.t898__icon-whatsapp_wrapper');if(whatsApp){var whatsAppHref=whatsApp.getAttribute('href');if(whatsAppHref&&(whatsAppHref.indexOf('whatsapp://')>-1||whatsAppHref.indexOf('wa.me')>-1)){t898_removeExtraSymbolsFromWhatsApp(whatsApp,whatsAppHref)}}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t898_removeExtraSymbolsFromWhatsApp(whatsApp,whatsAppHref){if(whatsAppHref&&whatsAppHref.indexOf('?text=')!==-1){var whatsAppHrefArr=whatsAppHref.split('?text=');whatsAppHrefArr[0]=whatsAppHrefArr[0].replace(/[\(\)+-]/g,'');whatsAppHref=whatsAppHrefArr[0]+'?text='+whatsAppHrefArr[1]}else{whatsAppHref=whatsAppHref.replace(/[\(\)+-]/,'')}
whatsApp.setAttribute('href',whatsAppHref)}